version: '3.7'
services:
  psql:
    restart: always
    image: postgres
    container_name: psql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
    volumes:
      - psql_data:/var/lib/postgresql/data

  superset:
    container_name: superset_demo
    restart: always
    build: ./superset
    image: superset_server
    volumes:
     - ./superset/superset-conf/config:/etc/superset
     - ./superset/superset-conf/data:/var/lib/superset
     - superset_demo:/app/superset_home
    ports:
     - "8088:8088"
    env_file:
      - .env
    environment:
     - SUPERSET_SECRET_KEY=${SUPERSET_SECRET_KEY}

volumes:
  psql_data:
  superset_demo: